# Generated by Django 3.2 on 2021-04-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nominal_price', models.FloatField()),
                ('lowest_price', models.FloatField()),
                ('item_url', models.CharField(max_length=500)),
            ],
        ),
    ]
